### ISSUE TITLE
Wrong link to Examples

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar-ui-qribbon#18]
**Describe the bug**
Link to the examples has a wrong target to 
`https://quasarframework.github.io/app-extension-qribbon/examples` instead of
`https://quasarframework.github.io/quasar-ui-qribbon/examples`

**To Reproduce**
1. Go to [Documentation Page](https://quasarframework.github.io/quasar-ui-qribbon/docs)
2. Click on Examples can be found `here`

**Expected behavior**
Open live examples `https://quasarframework.github.io/quasar-ui-qribbon/examples`

**Comment by hawkeye64** [comment]
This has been resolved in an earlier fix
