### ISSUE TITLE
Problem with leafs and overflow

### ISSUE THREAD

**Issue by Sfinx** [quasarframework/quasar-ui-qribbon#20]
I'd like to have the q-card with ribbon and no horisontal scroll bar. But ribbon leafs dissapeared when adding the "overflow-x: hidden;" as below. What I'm doing wrong ?

```
<q-card class="bg-grey-2" style="overflow-x: hidden; max-width: 85vw; max-height: 85vh;">
      <div class="box-ribbon-wrapper">
        <div class="flex justify-between q-pt-xl">
          <q-ribbon class="q-pb-md" background-color="primary" size="full" style="width: 100%; font-size: 3vh" glow glow-iteration count="1" inline>Ribbon Text</q-ribbon>
        </div>
      </div>
</q-card>
```

**Comment by hawkeye64** [comment]
@Sfinx It'd be way helpful if you can provide a mock-up of what you are trying to achieve and then maybe we can help you get the rest of the way.
I created a Codepen you can lay with here: https://codepen.io/Hawkeye64/pen/OJXMpYq

**Comment by Sfinx** [comment]
> I created a Codepen you can lay with here: https://codepen.io/Hawkeye64/pen/OJXMpYq

Thanks ! Please paste the following code to codepen example - And you will see no leafs. If you will remove "class=scroll" from q-card the leafs magically appears ;)

```
<div id="q-app">
  <div class="q-my-lg q-pa-md" style="max-width: 800px; width: 100%;">
  <q-card class="scroll" style="border: 1px solid black; width: 90%; height: 70px;">
      <div class="box-ribbon-wrapper">
        <div class="flex justify-between">
          <q-ribbon class="q-pb-md left-ribbon" style="width: 100%; font-size: 3vh" size="full" leaf-position="bottom" >Ribbon Text</q-ribbon>
        </div>
      </div>
  </q-card>
  </div>
</div>
```

**Comment by hawkeye64** [comment]
@Sfinx I see what you are saying. The "scroll" has `overflow: auto`, that's why you get the horizontal scrollbar. You can't see the one on the left because it's a negative margin. You should put the QRibbon outside of the scroll (like on top, for example) or don't make the QRibbon 100% of a scrolled area.
Here's a different example: https://codepen.io/Hawkeye64/pen/mdEVoWe
