### ISSUE TITLE
SassError: semicolons aren't allowed in the indented syntax

### ISSUE THREAD

**Issue by KevinYang0120** [quasarframework/quasar-ui-qribbon#21]
**Describe the bug**
is there something wrong with sass?

**Screenshots**
![image](https://user-images.githubusercontent.com/30248187/101113029-7b8f4000-3619-11eb-8822-bef55d9fd4cf.png)

**Comment by hawkeye64** [comment]
@KevinYang0120 Please update to latest (v1.0.0-beta.15)

**Comment by zachmanpro** [comment]
This is still an issue
